extends: ['airbnb-base', 'plugin:@typescript-eslint/recommended']
plugins: ['@typescript-eslint']
parser: '@typescript-eslint/parser'
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  camelcase: 0
env:
  commonjs: true
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 2018
globals:
  __: true
  expect: true
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
